# Generated by Django 3.1.7 on 2021-04-04 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210404_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='vkuser',
            name='name',
            field=models.CharField(default='', max_length=255),
        ),
    ]
