# Generated by Django 3.1.7 on 2021-04-04 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_auto_20210404_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vkuser',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
