# Generated by Django 3.1.7 on 2021-04-04 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210404_1130'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='from_id',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='owner_id',
            new_name='author',
        ),
    ]
